### ISSUE TITLE
Implementar capa de network

### ISSUE THREAD

**Issue by vamarmu** [vamarmu/Stockify#2]
Con Retrofit  comunicar con el API : alphavantage.co/ 

- Search Endpoint : https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=tesco&apikey=demo
- Company Overview  :  https://www.alphavantage.co/query?function=OVERVIEW&symbol=IBM&apikey=demo

**Comment by czerewacz** [comment]
@vamarmu  perfecto, esta asignamela a mi porfa.
